version: '3.1'
services:
  client:
    container_name: client
    image: tanveerinvoicereg.azurecr.io/client-prod
    build:
      dockerfile: ./client/Dockerfile
      target: production
    env_file:
      - client/.env
    ports:
      - '80:80'
    depends_on:
      - server
      - mongo
    links:
      - server
      - mongo
  server:
    container_name: server
    image: tanveerinvoicereg.azurecr.io/server-prod
    build:
      dockerfile: ./server/Dockerfile
    env_file:
      - server/.env
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: mongo
    container_name: MONGODB
    ports:
      - '27017'    
